
services:
  server:
    network_mode: "host"
    depends_on: {}
    deploy:
      restart_policy:
        condition: any
    build: ./yellow-server/
    volumes:
      - ./yellow-server:/app/app
      - ./yellow-server-common:/app/lib/yellow-server-common

