#services:
#
#  mariadb-init: null
#
#  common-init: null
#
#  server-init: null
#
#  server:
#    volumes: null
#
#  mariadb:
#    volumes: null
#
#  client:
#    volumes: null
#
#  messages:
#    volumes: null
#
#  admin:
#    volumes: null
#
#
#
