
services:
  server:
    network_mode: "host"
    depends_on: {}
    deploy:
      restart_policy:
        condition: any
    build: ./yellow-server/
    volumes:
      - ./yellow-server:/app/app
      - ./yellow-server-common:/app/lib/yellow-server-common
      - ./yellow-server-settings.json:/app/yellow-server-settings.json
    environment:
      - VITE_YELLOW_SETTINGS_PATH=/app/yellow-server-settings.json