receivers:
    otlp:
        protocols:
            grpc:
            http:

processors:
    batch:
  
exporters:
    otlp/elastic:
        endpoint: "127.0.0.1:8200"
#        tls:
#            insecure: true

    debug:
        verbosity: detailed
        sampling_initial: 5
        sampling_thereafter: 200

service:
    pipelines:
        traces:
            receivers: [otlp]
            processors: [batch]
            exporters: [debug, otlp/elastic]
        logs:
            receivers: [otlp]
            processors: []
            exporters: [debug, otlp/elastic]
