name: E2E Tests

on:
  push:
    branches: [ "**" ]
#  pull_request:
#    branches: [ master ]

jobs:
  e2e-tests:
    uses: ./.github/workflows/shared-e2e.yml
    # No inputs are needed as we're testing yellow-dev itself