name: E2E Tests

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
    
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
    
    - name: Install global npm packages
      run: npm install -g npm npx
    
    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Install Playwright
      run: |
        cd yellow-client
        npm ci
        npx playwright install --with-deps
    
    - name: Install Fish Shell and MariaDB Client
      run: |
        sudo apt-get update
        sudo apt-get install -y fish mariadb-client
    
    - name: Run E2E Tests
      run: python scripts/run_compose_and_test.py
