name: E2E Tests

on:
  push:
    branches: [ "**" ]
#  pull_request:
#    branches: [ master ]

jobs:
  e2e-tests:
    uses: ./.github/workflows/shared-e2e.yml
    with:
      run_client_tests: true
      run_admin_tests: true
      run_stack_tests: true